// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: token.proto

package localfileserver.protobuf;

public final class TokenInfo {
  private TokenInfo() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface TokenOrBuilder extends
      // @@protoc_insertion_point(interface_extends:localfileserver.protobuf.Token)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string value = 1;</code>
     * @return The value.
     */
    java.lang.String getValue();
    /**
     * <code>string value = 1;</code>
     * @return The bytes for value.
     */
    com.google.protobuf.ByteString
        getValueBytes();

    /**
     * <code>.localfileserver.protobuf.Token.TokenType type = 2;</code>
     * @return The enum numeric value on the wire for type.
     */
    int getTypeValue();
    /**
     * <code>.localfileserver.protobuf.Token.TokenType type = 2;</code>
     * @return The type.
     */
    localfileserver.protobuf.TokenInfo.Token.TokenType getType();

    /**
     * <code>int64 last_time = 3;</code>
     * @return The lastTime.
     */
    long getLastTime();

    /**
     * <code>bool isValid = 4;</code>
     * @return The isValid.
     */
    boolean getIsValid();
  }
  /**
   * Protobuf type {@code localfileserver.protobuf.Token}
   */
  public  static final class Token extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:localfileserver.protobuf.Token)
      TokenOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Token.newBuilder() to construct.
    private Token(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Token() {
      value_ = "";
      type_ = 0;
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new Token();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Token(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              value_ = s;
              break;
            }
            case 16: {
              int rawValue = input.readEnum();

              type_ = rawValue;
              break;
            }
            case 24: {

              lastTime_ = input.readInt64();
              break;
            }
            case 32: {

              isValid_ = input.readBool();
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return localfileserver.protobuf.TokenInfo.internal_static_localfileserver_protobuf_Token_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return localfileserver.protobuf.TokenInfo.internal_static_localfileserver_protobuf_Token_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              localfileserver.protobuf.TokenInfo.Token.class, localfileserver.protobuf.TokenInfo.Token.Builder.class);
    }

    /**
     * Protobuf enum {@code localfileserver.protobuf.Token.TokenType}
     */
    public enum TokenType
        implements com.google.protobuf.ProtocolMessageEnum {
      /**
       * <code>TEMP = 0;</code>
       */
      TEMP(0),
      /**
       * <code>FOREVER = 1;</code>
       */
      FOREVER(1),
      UNRECOGNIZED(-1),
      ;

      /**
       * <code>TEMP = 0;</code>
       */
      public static final int TEMP_VALUE = 0;
      /**
       * <code>FOREVER = 1;</code>
       */
      public static final int FOREVER_VALUE = 1;


      public final int getNumber() {
        if (this == UNRECOGNIZED) {
          throw new java.lang.IllegalArgumentException(
              "Can't get the number of an unknown enum value.");
        }
        return value;
      }

      /**
       * @param value The numeric wire value of the corresponding enum entry.
       * @return The enum associated with the given numeric wire value.
       * @deprecated Use {@link #forNumber(int)} instead.
       */
      @java.lang.Deprecated
      public static TokenType valueOf(int value) {
        return forNumber(value);
      }

      /**
       * @param value The numeric wire value of the corresponding enum entry.
       * @return The enum associated with the given numeric wire value.
       */
      public static TokenType forNumber(int value) {
        switch (value) {
          case 0: return TEMP;
          case 1: return FOREVER;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<TokenType>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static final com.google.protobuf.Internal.EnumLiteMap<
          TokenType> internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<TokenType>() {
              public TokenType findValueByNumber(int number) {
                return TokenType.forNumber(number);
              }
            };

      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        return getDescriptor().getValues().get(ordinal());
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return localfileserver.protobuf.TokenInfo.Token.getDescriptor().getEnumTypes().get(0);
      }

      private static final TokenType[] VALUES = values();

      public static TokenType valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        if (desc.getIndex() == -1) {
          return UNRECOGNIZED;
        }
        return VALUES[desc.getIndex()];
      }

      private final int value;

      private TokenType(int value) {
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:localfileserver.protobuf.Token.TokenType)
    }

    public static final int VALUE_FIELD_NUMBER = 1;
    private volatile java.lang.Object value_;
    /**
     * <code>string value = 1;</code>
     * @return The value.
     */
    public java.lang.String getValue() {
      java.lang.Object ref = value_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        value_ = s;
        return s;
      }
    }
    /**
     * <code>string value = 1;</code>
     * @return The bytes for value.
     */
    public com.google.protobuf.ByteString
        getValueBytes() {
      java.lang.Object ref = value_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        value_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int TYPE_FIELD_NUMBER = 2;
    private int type_;
    /**
     * <code>.localfileserver.protobuf.Token.TokenType type = 2;</code>
     * @return The enum numeric value on the wire for type.
     */
    public int getTypeValue() {
      return type_;
    }
    /**
     * <code>.localfileserver.protobuf.Token.TokenType type = 2;</code>
     * @return The type.
     */
    public localfileserver.protobuf.TokenInfo.Token.TokenType getType() {
      @SuppressWarnings("deprecation")
      localfileserver.protobuf.TokenInfo.Token.TokenType result = localfileserver.protobuf.TokenInfo.Token.TokenType.valueOf(type_);
      return result == null ? localfileserver.protobuf.TokenInfo.Token.TokenType.UNRECOGNIZED : result;
    }

    public static final int LAST_TIME_FIELD_NUMBER = 3;
    private long lastTime_;
    /**
     * <code>int64 last_time = 3;</code>
     * @return The lastTime.
     */
    public long getLastTime() {
      return lastTime_;
    }

    public static final int ISVALID_FIELD_NUMBER = 4;
    private boolean isValid_;
    /**
     * <code>bool isValid = 4;</code>
     * @return The isValid.
     */
    public boolean getIsValid() {
      return isValid_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getValueBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, value_);
      }
      if (type_ != localfileserver.protobuf.TokenInfo.Token.TokenType.TEMP.getNumber()) {
        output.writeEnum(2, type_);
      }
      if (lastTime_ != 0L) {
        output.writeInt64(3, lastTime_);
      }
      if (isValid_ != false) {
        output.writeBool(4, isValid_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getValueBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, value_);
      }
      if (type_ != localfileserver.protobuf.TokenInfo.Token.TokenType.TEMP.getNumber()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(2, type_);
      }
      if (lastTime_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(3, lastTime_);
      }
      if (isValid_ != false) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(4, isValid_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof localfileserver.protobuf.TokenInfo.Token)) {
        return super.equals(obj);
      }
      localfileserver.protobuf.TokenInfo.Token other = (localfileserver.protobuf.TokenInfo.Token) obj;

      if (!getValue()
          .equals(other.getValue())) return false;
      if (type_ != other.type_) return false;
      if (getLastTime()
          != other.getLastTime()) return false;
      if (getIsValid()
          != other.getIsValid()) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + VALUE_FIELD_NUMBER;
      hash = (53 * hash) + getValue().hashCode();
      hash = (37 * hash) + TYPE_FIELD_NUMBER;
      hash = (53 * hash) + type_;
      hash = (37 * hash) + LAST_TIME_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getLastTime());
      hash = (37 * hash) + ISVALID_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
          getIsValid());
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static localfileserver.protobuf.TokenInfo.Token parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static localfileserver.protobuf.TokenInfo.Token parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static localfileserver.protobuf.TokenInfo.Token parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static localfileserver.protobuf.TokenInfo.Token parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static localfileserver.protobuf.TokenInfo.Token parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static localfileserver.protobuf.TokenInfo.Token parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static localfileserver.protobuf.TokenInfo.Token parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static localfileserver.protobuf.TokenInfo.Token parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static localfileserver.protobuf.TokenInfo.Token parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static localfileserver.protobuf.TokenInfo.Token parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static localfileserver.protobuf.TokenInfo.Token parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static localfileserver.protobuf.TokenInfo.Token parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(localfileserver.protobuf.TokenInfo.Token prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code localfileserver.protobuf.Token}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:localfileserver.protobuf.Token)
        localfileserver.protobuf.TokenInfo.TokenOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return localfileserver.protobuf.TokenInfo.internal_static_localfileserver_protobuf_Token_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return localfileserver.protobuf.TokenInfo.internal_static_localfileserver_protobuf_Token_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                localfileserver.protobuf.TokenInfo.Token.class, localfileserver.protobuf.TokenInfo.Token.Builder.class);
      }

      // Construct using localfileserver.protobuf.TokenInfo.Token.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        value_ = "";

        type_ = 0;

        lastTime_ = 0L;

        isValid_ = false;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return localfileserver.protobuf.TokenInfo.internal_static_localfileserver_protobuf_Token_descriptor;
      }

      @java.lang.Override
      public localfileserver.protobuf.TokenInfo.Token getDefaultInstanceForType() {
        return localfileserver.protobuf.TokenInfo.Token.getDefaultInstance();
      }

      @java.lang.Override
      public localfileserver.protobuf.TokenInfo.Token build() {
        localfileserver.protobuf.TokenInfo.Token result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public localfileserver.protobuf.TokenInfo.Token buildPartial() {
        localfileserver.protobuf.TokenInfo.Token result = new localfileserver.protobuf.TokenInfo.Token(this);
        result.value_ = value_;
        result.type_ = type_;
        result.lastTime_ = lastTime_;
        result.isValid_ = isValid_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof localfileserver.protobuf.TokenInfo.Token) {
          return mergeFrom((localfileserver.protobuf.TokenInfo.Token)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(localfileserver.protobuf.TokenInfo.Token other) {
        if (other == localfileserver.protobuf.TokenInfo.Token.getDefaultInstance()) return this;
        if (!other.getValue().isEmpty()) {
          value_ = other.value_;
          onChanged();
        }
        if (other.type_ != 0) {
          setTypeValue(other.getTypeValue());
        }
        if (other.getLastTime() != 0L) {
          setLastTime(other.getLastTime());
        }
        if (other.getIsValid() != false) {
          setIsValid(other.getIsValid());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        localfileserver.protobuf.TokenInfo.Token parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (localfileserver.protobuf.TokenInfo.Token) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object value_ = "";
      /**
       * <code>string value = 1;</code>
       * @return The value.
       */
      public java.lang.String getValue() {
        java.lang.Object ref = value_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          value_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string value = 1;</code>
       * @return The bytes for value.
       */
      public com.google.protobuf.ByteString
          getValueBytes() {
        java.lang.Object ref = value_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          value_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string value = 1;</code>
       * @param value The value to set.
       * @return This builder for chaining.
       */
      public Builder setValue(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        value_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string value = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearValue() {
        
        value_ = getDefaultInstance().getValue();
        onChanged();
        return this;
      }
      /**
       * <code>string value = 1;</code>
       * @param value The bytes for value to set.
       * @return This builder for chaining.
       */
      public Builder setValueBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        value_ = value;
        onChanged();
        return this;
      }

      private int type_ = 0;
      /**
       * <code>.localfileserver.protobuf.Token.TokenType type = 2;</code>
       * @return The enum numeric value on the wire for type.
       */
      public int getTypeValue() {
        return type_;
      }
      /**
       * <code>.localfileserver.protobuf.Token.TokenType type = 2;</code>
       * @param value The enum numeric value on the wire for type to set.
       * @return This builder for chaining.
       */
      public Builder setTypeValue(int value) {
        type_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>.localfileserver.protobuf.Token.TokenType type = 2;</code>
       * @return The type.
       */
      public localfileserver.protobuf.TokenInfo.Token.TokenType getType() {
        @SuppressWarnings("deprecation")
        localfileserver.protobuf.TokenInfo.Token.TokenType result = localfileserver.protobuf.TokenInfo.Token.TokenType.valueOf(type_);
        return result == null ? localfileserver.protobuf.TokenInfo.Token.TokenType.UNRECOGNIZED : result;
      }
      /**
       * <code>.localfileserver.protobuf.Token.TokenType type = 2;</code>
       * @param value The type to set.
       * @return This builder for chaining.
       */
      public Builder setType(localfileserver.protobuf.TokenInfo.Token.TokenType value) {
        if (value == null) {
          throw new NullPointerException();
        }
        
        type_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <code>.localfileserver.protobuf.Token.TokenType type = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearType() {
        
        type_ = 0;
        onChanged();
        return this;
      }

      private long lastTime_ ;
      /**
       * <code>int64 last_time = 3;</code>
       * @return The lastTime.
       */
      public long getLastTime() {
        return lastTime_;
      }
      /**
       * <code>int64 last_time = 3;</code>
       * @param value The lastTime to set.
       * @return This builder for chaining.
       */
      public Builder setLastTime(long value) {
        
        lastTime_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int64 last_time = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearLastTime() {
        
        lastTime_ = 0L;
        onChanged();
        return this;
      }

      private boolean isValid_ ;
      /**
       * <code>bool isValid = 4;</code>
       * @return The isValid.
       */
      public boolean getIsValid() {
        return isValid_;
      }
      /**
       * <code>bool isValid = 4;</code>
       * @param value The isValid to set.
       * @return This builder for chaining.
       */
      public Builder setIsValid(boolean value) {
        
        isValid_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>bool isValid = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearIsValid() {
        
        isValid_ = false;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:localfileserver.protobuf.Token)
    }

    // @@protoc_insertion_point(class_scope:localfileserver.protobuf.Token)
    private static final localfileserver.protobuf.TokenInfo.Token DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new localfileserver.protobuf.TokenInfo.Token();
    }

    public static localfileserver.protobuf.TokenInfo.Token getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Token>
        PARSER = new com.google.protobuf.AbstractParser<Token>() {
      @java.lang.Override
      public Token parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Token(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Token> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Token> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public localfileserver.protobuf.TokenInfo.Token getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_localfileserver_protobuf_Token_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_localfileserver_protobuf_Token_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\013token.proto\022\030localfileserver.protobuf\"" +
      "\227\001\n\005Token\022\r\n\005value\030\001 \001(\t\0227\n\004type\030\002 \001(\0162)" +
      ".localfileserver.protobuf.Token.TokenTyp" +
      "e\022\021\n\tlast_time\030\003 \001(\003\022\017\n\007isValid\030\004 \001(\010\"\"\n" +
      "\tTokenType\022\010\n\004TEMP\020\000\022\013\n\007FOREVER\020\001B\013B\tTok" +
      "enInfob\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_localfileserver_protobuf_Token_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_localfileserver_protobuf_Token_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_localfileserver_protobuf_Token_descriptor,
        new java.lang.String[] { "Value", "Type", "LastTime", "IsValid", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
