debug: true
logging:
  pattern:
    console: '%d{${LOG_DATEFORMAT_PATTERN:HH:mm:ss.SSS}} %clr(${LOG_LEVEL_PATTERN:-%5p}) %clr(${PID:- }){magenta} %clr(-){faint} %clr([%10.10t]){faint} %clr(%-36.36logger{32}){cyan} %clr(:){faint} %m%n'
    file: '%d{${LOG_DATEFORMAT_PATTERN:yyyy-MM-dd HH:mm:ss.SSS}} ${LOG_LEVEL_PATTERN:-%5p} ${PID:- } - [%10.10t] %-36.36logger{32} : %m%n'
  file: 'fileUpload.log'
  level:
    root: debug
    org.jiong: debug
    org.springframework.boot: info
    org.spring: debug
    com.jfinal: info
    org.apache.tomcat: info
    org.apache.catalina: info
    org.apache.coyote: info
    sun.rmi: info
    javax.management.remote: info
server:
  port: 8078

spring:
  mvc:
    view:
      suffix: '.html'
      prefix: '/templates/'
