dubbo:
  application:
    name: server
    qos-port: 24222
  registry:
    address: 111.229.29.192:2181
    protocol: zookeeper
    timeout: 10000
  provider:
    timeout: 60000
spring:
  devtools:
    livereload:
      port: 35012
  main:
    allow-bean-definition-overriding: true
debug: true