dubbo:
  application:
    name: server
  registry:
    address: 111.229.29.192:2181
    protocol: zookeeper
    timeout: 10000
spring:
  devtools:
    livereload:
      port: 35012
  main:
    allow-bean-definition-overriding: true