
dubbo:
  application:
    name: client
  registry:
    address: 127.0.0.1:2181
    protocol: zookeeper
    check: false
    timeout: 10000
  consumer:
    timeout: 60000
spring:
  main:
    allow-bean-definition-overriding: true
  devtools:
    livereload:
      port: 35013
  servlet:
    multipart:
      max-file-size: 500MB
      max-request-size: 500MB

server:
  servlet:
    context-path: /client
  port: 8081
debug: true

  {"2181/tcp":[{"HostIp":"","HostPort":"2181"}],"8081/tcp":[{"HostIp":"","HostPort":"8081"}]